version: '2'
services:
  proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - '80:80'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
  main:
    image: kaerimichi/alnode:latest
    working_dir: /app
    ports:
      - '8080'
    volumes:
      - './:/app'
    environment:
      VIRTUAL_HOST: 'ahgora-api.local'
    command: ./.init
